### ISSUE TITLE
[Error] Convert docx to html5 with --extract-media

### ISSUE THREAD

**Issue by ncdai** [eshinn/node-pandoc#5]
I want to convert docx to html5 with media.
This is my code
![screen shot 2018-03-01 at 9 43 01 pm](https://user-images.githubusercontent.com/10192821/36850612-dc0edfee-1d99-11e8-8704-93a10bf50c27.png)
When i run app, it has error:
![111](https://user-images.githubusercontent.com/10192821/36850744-237c3c1e-1d9a-11e8-970a-4649156a9040.png)
How to fix it?
Thank you!

**Comment by ncdai** [comment]
I run app on DigitalOcean (Ubuntu Server 16.04).

**Comment by ankurpowar** [comment]
I am getting this error too. when I run the code on windows 10 it works without error. but when i run this on ubuntu server 18.04 it throws the same error even though it converts the docx to html and extracts the media to the corresponding folder successfully.
the problem is when i use this in my express app due to this error I could not continue to next process because the error can be else for another time.
Anyone got the solution?

**Comment by ankurpowar** [comment]
well I found the solution. the pandoc version is older in ubuntu package manager. So if you are using pandoc and this error occures (or any) first check if you are using latest version. 
I used the .deb installer from pandoc official git repo:
https://github.com/jgm/pandoc/releases/tag/2.7.2
and it worked.

**Comment by ncdai** [comment]
Thanks @ankurpowar 😄
